version: "3.3"

services:
  proxy:
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./acme.json:/certificates/acme.json
    command:
      - --providers.docker
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --certificatesresolvers.le.acme.email=${NS_ECOTEKA_PROXY_CERTIFICATESRESOLVERS_LE_ACME_EMAIL}
      - --certificatesresolvers.le.acme.storage=/certificates/acme.json
      - --certificatesresolvers.le.acme.tlschallenge=true
      - --accesslog
      - --log
    labels:
      # Global redirection: http to https
      - traefik.http.routers.web-catchall.rule=HostRegexp(`{host:(www\.)?.+}`)
      - traefik.http.routers.web-catchall.entrypoints=web
      - traefik.http.routers.web-catchall.middlewares=wwwtohttps

      # Global redirection: https (www.) to https
      - traefik.http.routers.wwwsecure-catchall.rule=HostRegexp(`{host:(www\.).+}`)
      - traefik.http.routers.wwwsecure-catchall.entrypoints=websecure
      - traefik.http.routers.wwwsecure-catchall.tls=true
      - traefik.http.routers.wwwsecure-catchall.middlewares=wwwtohttps

      # Middleware: http(s)://(www.) to  https://
      - traefik.http.middlewares.wwwtohttps.redirectregex.regex=^https?://(?:www\.)?(.+)
      - traefik.http.middlewares.wwwtohttps.redirectregex.replacement=https://$${1}
      - traefik.http.middlewares.wwwtohttps.redirectregex.permanent=true

      # Let's Encrypt
      - traefik.http.services.proxy.loadbalancer.server.port=80
      - traefik.http.routers.wwwsecure.tls.domains[0].main=${NS_ECOTEKA_DOMAIN_NAME}
      - traefik.http.routers.wwwsecure.tls.domains[0].sans=www.${NS_ECOTEKA_DOMAIN_NAME}
      - traefik.http.routers.wwwsecure.tls.certresolver=le

  backend:
    labels:
      - traefik.http.routers.backend.entrypoints=websecure
      - traefik.http.routers.backend.tls=true

  frontend:
    labels:
      - traefik.http.routers.frontend.entrypoints=websecure
      - traefik.http.routers.frontend.tls=true
      - traefik.http.services.frontend.loadbalancer.server.port=80
