version: '3.3'

services:
  proxy:
    image: traefik:v2.2
    networks:
      - traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      - --providers.docker
      - --providers.docker.exposedbydefault=false
      - --accesslog
      - --log
      - --api
    
  db:
    image: postgres:12
    networks:
      - traefik
    volumes:
      - app-db-data:/var/lib/postgresql/data/pgdata
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata

  frontend:
    image: ${NS_ECOTEKA_FRONTEND_IMAGE}
    networks:
      - traefik

  backend:
    image: ${NS_ECOTEKA_BACKEND_IMAGE}
    networks:
      - traefik

volumes:
  app-db-data:

networks: 
  traefik: 
    external: true
