version: "3.3"

services:
  proxy:
    ports:
      - "${NS_ECOTEKA_PROXY_HTTP_PORT}:80"
      - "${NS_ECOTEKA_PROXY_API_PORT}:8080"
    command:
      - --providers.docker
      - --providers.docker.exposedbydefault=false
      - --accesslog
      - --log
      - --api
      - --api.insecure=true

  db:
    ports:
      - "${NS_ECOTEKA_DB_PORT}:5432"

  mail:
    image: ${NS_ECOTEKA_MAIL_IMAGE}
    networks:
      - traefik
    labels:
      - traefik.enable=true
      - traefik.http.routers.mail.rule=PathPrefix(`/mail`)
      - traefik.http.routers.mail.middlewares=mail-stripprefix
      - traefik.http.middlewares.mail-stripprefix.stripprefix.prefixes=/mail
      - traefik.http.services.mail.loadbalancer.server.port=80
    environment:
      - MAILDEV_BASE_PATHNAME=/mail

  backend:
    image: ecoteka-backend:dev
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
    command: /start-reload.sh
    ports:
      - "5678:5678"

  celery_worker:
    image: ecoteka-backend:dev
    volumes:
      - ./backend/app:/app

  frontend:
    image: ecoteka-frontend:dev
    build:
      context: ./frontend
      dockerfile: .docker/Dockerfile.dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    labels:
      - traefik.http.services.frontend.loadbalancer.server.port=3000

  meilisearch:
    ports:
      - 7700:7700
