FROM node:15-buster-slim
ARG asset_prefix
WORKDIR /app
RUN apt-get update \
    && apt-get install -y libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb
COPY package.json .
RUN npm install
RUN npm install -g npm-check-updates 
COPY . .
RUN npx next telemetry disable
COPY .docker/start-dev.sh /docker-entrypoint.sh

EXPOSE 3000

ENTRYPOINT [ "/docker-entrypoint.sh" ]